### ISSUE TITLE
No tray icon after launch

### ISSUE THREAD

**Issue by notuxius** [hereafter/power-brightness#1]
There is "Power Brightness" process in Task Manager but there is no tray icon
Windows 10 1809 17763.379

**Comment by hereafter** [comment]
Hi, notuxius, thanks for reporting issues.
I'd like to gather more information about the issue you are having.

**1. First, what version is it on your machine?**
To find out, please kindly launch "Power Brightness Help" from "start" menu.

### 2. Have you checked if it is hidden by default?

https://support.microsoft.com/en-us/help/30031/windows-10-customize-taskbar-notification-area
or 
https://www.brucebnews.com/2017/03/windows-10-tip-drag-icons-into-the-notification-area-on-the-taskbar/

**3. Have you tried restart "explorer.exe"?** 
Here are steps you could follow to restart explorer.exe to see if the notification icons are recovered.
https://mywindowshub.com/how-to-restart-explorer-exe-process-in-windows-10/

**4. Could you please have a run of "tasklist" in Command Prompt**

https://github.com/hereafter/power-brightness/blob/master/issues/tasklist.png

and paste the  text dump here

I could investigate further to see if there is any 3rd party applications are interferencing

**5. Above all , have you tried re-install the app and restart the computer?**
a desperate move

here is the latest version I tried.

https://github.com/hereafter/power-brightness/blob/master/issues/test.png

Thanks

**Comment by notuxius** [comment]
Brightness version 1.2.18.0
No change after restarting explorer

[tasklist.txt](https://github.com/hereafter/power-brightness/files/3073689/tasklist.txt)

**Comment by hereafter** [comment]
In the past few weeks, I have seen 61 crashes, 60 of them are opt-out of error details. However there is one with detailed report, and guess what it is related to the this issue.

I am pretty sure this bug is now fixed in commin gupdate 1.3.22.0

Thanks

Here is more technique details

[https://github.com/hereafter/power-brightness/wiki/Quest-for-a-mysterious-bug](url)

Please kindly help to verify if you got the update next week

**Comment by hereafter** [comment]
@notuxius the fix is up in the windows store, please have a look if you are still interested.

**Comment by notuxius** [comment]
Still no tray icon after launch, version 1.4.25.0 - maybe some prev version configuration files leftovers?

**Comment by notuxius** [comment]
@hereafter how to disable privacy settings for sending proper crash reports?)
